SELECT 
       SUM(G.SCORE) AS SCORE
     , E.EMP_NO
     , E.EMP_NAME
     , E.POSITION
     , E.EMAIL
  FROM HR_EMPLOYEES E
  JOIN HR_GRADE G
    ON G.EMP_NO = E.EMP_NO
 WHERE G.YEAR = 2022   
 GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
HAVING SUM(G.SCORE) = (
    SELECT MAX(SCORE)
    FROM (
        SELECT SUM(SCORE) AS SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) A
);